### ISSUE TITLE
breaks with `check@2`

### ISSUE THREAD

**Issue by ianstormtaylor** [clintonskakun/removeAttributes#2]
It's breaking currently with:

```
     TypeError: Cannot read property 'unemptyString' of undefined
      at removeAttrs (node_modules/remove-attributes/removeAttributes.js:26:15)
      at clean (test/rendering/index.js:90:41)
      at Context.<anonymous> (test/rendering/index.js:59:38)
```

It looks like check renamed `verify` so it no longer exists.

**Comment by clintonskakun** [comment]
This is now merged. Thanks for the MR.
